// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYyMTm_aqSM5o4mUvIjEDTilsXCRllz6c',
    appId: '1:919835922577:web:d407e0ccdc59f39aa06f30',
    messagingSenderId: '919835922577',
    projectId: 'yemek-1eee2',
    authDomain: 'yemek-1eee2.firebaseapp.com',
    storageBucket: 'yemek-1eee2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGT_Zzeo1QdL564F_C5cWOWXDaGjm31ik',
    appId: '1:919835922577:android:d737c439c1511faba06f30',
    messagingSenderId: '919835922577',
    projectId: 'yemek-1eee2',
    storageBucket: 'yemek-1eee2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOnn0acfxhcpO1XL96kz0BDnuujHa3dak',
    appId: '1:919835922577:ios:ba47520686b29d87a06f30',
    messagingSenderId: '919835922577',
    projectId: 'yemek-1eee2',
    storageBucket: 'yemek-1eee2.firebasestorage.app',
    iosBundleId: 'com.example.yemekTarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOnn0acfxhcpO1XL96kz0BDnuujHa3dak',
    appId: '1:919835922577:ios:ba47520686b29d87a06f30',
    messagingSenderId: '919835922577',
    projectId: 'yemek-1eee2',
    storageBucket: 'yemek-1eee2.firebasestorage.app',
    iosBundleId: 'com.example.yemekTarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYyMTm_aqSM5o4mUvIjEDTilsXCRllz6c',
    appId: '1:919835922577:web:77a879a5cef48733a06f30',
    messagingSenderId: '919835922577',
    projectId: 'yemek-1eee2',
    authDomain: 'yemek-1eee2.firebaseapp.com',
    storageBucket: 'yemek-1eee2.firebasestorage.app',
  );

}